<a name="topage"></a>

# 029.Handle a Rejected Promise with catch

### [ Notes ]
  * `catch` method is executed immediately after your promise has been rejected.
  * `error` is the argument passed in to the reject method.

#### example #1

```sh
myPromise.catch(error => {
  
});
```

### [ Task ]
  1. Add the catch method to your promise. Use error as the parameter of its callback function and log error to the console.

### [ before ]

```sh
const makeServerRequest = new Promise((resolve, reject) => {
  // responseFromServer is set to false to represent an unsuccessful response from a server
  let responseFromServer = false;
    
  if(responseFromServer) {
    resolve("We got the data");
  } else {  
    reject("Data not received");
  }
});

makeServerRequest.then(result => {
  console.log(result);
});
```

### [ solution ]

```sh
const makeServerRequest = new Promise((resolve, reject) => {
  // responseFromServer is set to false to represent an unsuccessful response from a server
  let responseFromServer = false;
    
  if(responseFromServer) {
    resolve("We got the data");
  } else {  
    reject("Data not received");
  }
});

makeServerRequest.catch(error => {
  console.log(error);
});
```

### [ output result ]

```sh
Data not received
```

-----

### [ Thoughts ]

  1. `catch` method is executed immediately after your promise has been rejected.
  

<p align="right">(<a href="#topage">back to top</a>)</p>
<br/>
<br/>
